import Providers from "./redux/Providers"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body id="root" >
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    )
}
